/** Read-only Zeo One DP labels from com.roborock.wm/Zeo One/output/798.js. */
export const ZEO_ONE_STATUS_LABELS: Record<string, { alias: string; values: Record<number, string> }> = {
	"203": { alias: "status_name", values: {
		1: "Standby",
		2: "Checking",
		3: "Soaking",
		4: "Washing",
		5: "Rinsing",
		6: "Dewatering",
		7: "Drying",
		8: "Cooling",
		9: "Appointment",
		10: "Complete",
		11: "Updating",
		12: "SmartHosting",
		13: "SmartHostingWaiting",
	} },
	"204": { alias: "mode_name", values: {
		1: "Wash",
		2: "WashAndDry",
		3: "Dry",
	} },
	"205": { alias: "program_name", values: {
		1: "Mixed",
		2: "Quick",
		3: "Sterilization",
		4: "Wool",
		5: "Air",
		6: "CloudProgram",
		7: "HomeTextile",
		8: "Down",
		9: "Silk",
		10: "RinseAndDehydrate",
		11: "Dehydrate",
		12: "SelfClean",
		13: "Baby",
		14: "MitesRemoval",
		15: "Sports",
		16: "Night",
		17: "New",
		18: "Shirt",
		19: "ChemicalFiber",
		20: "Underwear",
		21: "Soft",
		22: "Strong",
		23: "CottonOrLinen",
		24: "Season",
		25: "Warm",
		26: "Bra",
		27: "Underpants",
		28: "Boiling",
		29: "Soaking",
		30: "Socks",
		31: "Towel",
		32: "MitesRemoval2",
		33: "Eco",
		34: "TwentyDegrees",
		35: "TShirt",
		36: "Dirt",
		37: "SmallThings",
		39: "Mixing",
	} },
};
