name: Bug report
description: Report a bug and upload your debug log file
title: "[BUG] "
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        ## Describe the bug
        A clear and concise description of what the bug is.

  - type: textarea
    id: bug_description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Describe the steps to reproduce the bug."
      placeholder: "List the steps here..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## âš ï¸ Debug Log Required (Strictly .txt only!)
        To analyze this issue, we **MUST** have a full debug log from the start of the adapter.

        ### ðŸ“– How to get a clean debug log:
        1. Go to the "Instances" tab in ioBroker.
        2. Set the "Log level" of your Roborock instance to **debug**.
        3. Go to the "Log" tab in ioBroker.
        4. Clear the current log.
        5. **Restart the Roborock adapter instance.**
        6. Wait at least **3 minutes** while the adapter starts up and the error occurs.
        7. Download the log file or copy the relevant part.
        8. **Save it as a `.txt` file.** (e.g., `debuglog.txt`)

        > [!IMPORTANT]
        > **Pasting the log directly into this issue description is FORBIDDEN.**
        > Upload the `.txt` file using the field below.

  - type: checkboxes
    id: log_confirmation
    attributes:
      label: "Log Confirmation"
      options:
        - label: "I have restarted the adapter in 'debug' mode and collected a log of at least 3 minutes."
          required: true
        - label: "I have saved the log as a `.txt` file and attached it below (DON'T PASTE!)."
          required: true

  - type: textarea
    id: debug_log_upload
    attributes:
      label: "Debug Log Upload (Drag & Drop .txt file here)"
      description: "DO NOT PASTE! Just drag and drop your .txt file into this field."
      placeholder: "Drag & drop file here (No pasting allowed!)."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Versions
        Please provide the following version information.

  - type: input
    id: adapter_version
    attributes:
      label: "Adapter Version"
      description: "Version of the adapter"
      placeholder: "<adapter-version>"
    validations:
      required: true

  - type: input
    id: js_controller_version
    attributes:
      label: "JS-Controller Version"
      description: "Version of the JS-Controller (use `iobroker -v` to determine this)"
      placeholder: "<js-controller-version>"
    validations:
      required: true

  - type: input
    id: node_version
    attributes:
      label: "Node.js Version"
      description: "Version of Node.js (use `node -v` to determine this)"
      placeholder: "<node-version>"
    validations:
      required: true

  - type: input
    id: os_name
    attributes:
      label: "Operating System"
      description: "Name of the operating system"
      placeholder: "<os-name>"
    validations:
      required: true

  - type: input
    id: firmware_version
    attributes:
      label: "Firmware version of device"
      description: "Version of firmware of the device"
      placeholder: "Version of firmware of the device"
    validations:
      required: true
