export const ADAPTER_ERROR_MAPPING: Record<number, string> = {
	1: "localization_strings_Main_Constants_0",
	2: "localization_strings_Main_Constants_3",
	3: "localization_strings_Main_Constants_6",
	4: "localization_strings_Main_Constants_9",
	5: "localization_strings_Main_Constants_12",
	6: "localization_strings_Main_Constants_15",
	7: "localization_strings_Main_Constants_18",
	8: "localization_strings_Main_Constants_21",
	9: "localization_strings_Main_Constants_24",
	10: "localization_strings_Main_Constants_27",
	11: "localization_strings_Main_Constants_30",
	12: "localization_strings_Main_Constants_33",
	13: "localization_strings_Common_Constants_10",
	14: "localization_strings_Main_Constants_39",
	15: "localization_strings_Main_Constants_42",
	16: "localization_strings_Main_Constants_45",
	17: "localization_strings_Main_Constants_48",
	18: "localization_strings_Main_Constants_51",
	19: "localization_strings_Main_Constants_54",
	21: "rubys_error_21_title",
	22: "rubys_error_22_title",
	23: "rubys_error_23_title",
	24: "error_robot_in_forbidden",
	25: "error_visual_sensor_title",
	26: "localization_strings_Main_Error_Constants_23",
	27: "tanos_s_error_27_title",
	28: "tanos_s_error_28_title",
	29: "tanos_s_error_29_title",
	30: "ImageFPSError",
	32: "collecting_dusk_error32_title",
	33: "collecting_dusk_error33_title",
	34: "collecting_dusk_error34_title",
	35: "collecting_dusk_error35_title",
	36: "error_mopping_roller1_title",
	37: "error_mopping_roller2_title",
	38: "error_clear_waterbox_hoare_title",
	39: "error_dirty_waterbox_hoare_title",
	40: "error_sink_strainer_hoare_title",
	41: "error_clear_waterbox_exception_title",
	42: "error_clean_bruch_exception_title",
	43: "error_main_frame_exception_title",
	44: "error_filter_screen_exception_title",
	45: "error_mopping_roller1_title",
	48: "error_up_water_title",
	49: "error_drain_water_title",
	51: "error_temperature_protection_title",
	52: "error_clean_carousel_unsetuped_title",
	53: "error_clean_carousel_water_full_title",
	54: "error_water_carriage_drop_title",
};

export const ADAPTER_ERRORS_EN: Record<string, string> = {
	"1": "LiDAR Sensor error",
	"2": "Bumper stuck",
	"3": "Wheels suspended",
	"4": "Cliff sensor error",
	"5": "Main brush jammed.",
	"6": "Side brush jammed.",
	"7": "The robot is stuck, or main wheels are jammed.",
	"8": "The robot is trapped or stuck.",
	"9": "Dustbin not installed",
	"10": "Filter is wet or blocked.",
	"11": "Strong magnetic field detected.",
	"12": "Low battery",
	"13": "Charging Error",
	"14": "Unit temperature protection",
	"15": "The wall sensor is dirty.",
	"16": "Robot is tilted",
	"17": "Side brush error",
	"18": "Fan error",
	"19": "Dock not connected to power",
	"21": "Vertical Bumper Error",
	"22": "Recharge Sensor Error",
	"23": "Could not Reach Dock",
	"24": "No-Go Zone or Invisible Wall detected",
	"25": "Camera Error",
	"26": "Wall sensor error",
	"27": "Jammed mop module",
	"28": "The robot may be on a carpet",
	"29": "Unable to cross the carpet",
	"32": "No dustbin or filter installed",
	"33": "Auto-Empty Dock fan error",
	"34": "Clean the Auto-Empty Dock bin",
	"35": "Auto-Empty Dock voltage error",
	"36": "Wash roller may be jammed.",
	"37": "Wash roller not lowered properly.",
	"38": "Check the clean water tank.",
	"39": "Check the dirty water tank.",
	"40": "Water filter not installed.",
	"41": "Clean water tank empty.",
	"42": "Check that the water filter has been correctly installed.",
	"43": "Positioning button Error",
	"44": "Check and secure the dirty water tank cover",
	"45": "Wash roller may be jammed.",
	"48": "Refill error",
	"49": "Drain error",
	"51": "Unit temperature protection",
	"52": "Please check the cleaning tray.",
	"53": "Cleaning tray full.",
	"54": "The mop mount fell off. "
};
