export const VACUUM_CONSTANTS = {
	errorCodes: {
		0: "No error",
		1: "Laser sensor fault",
		2: "Collision sensor fault",
		3: "Wheel floating",
		4: "Cliff sensor fault",
		5: "Main brush blocked",
		6: "Side brush blocked",
		7: "Wheel blocked",
		8: "Device stuck",
		9: "Dust bin missing",
		10: "Filter blocked",
		11: "Magnetic field detected",
		12: "Low battery",
		13: "Charging problem",
		14: "Battery failure",
		15: "Wall sensor fault",
		16: "Uneven surface",
		17: "Side brush failure",
		18: "Suction fan failure",
		19: "Unpowered charging station",
		20: "Unknown Error",
		21: "Laser pressure sensor problem",
		22: "Charge sensor problem",
		23: "Dock problem",
		24: "No-go zone or invisible wall detected",
		254: "Bin full",
		255: "Internal error",
		"-1": "Unknown Error",
	},
	stateCodes: {
		0: "Unknown",
		1: "Initiating",
		2: "Sleeping",
		3: "Idle",
		4: "Remote Control",
		5: "Cleaning",
		6: "Returning Dock",
		7: "Manual Mode",
		8: "Charging",
		9: "Charging Error",
		10: "Paused",
		11: "Spot Cleaning",
		12: "In Error",
		13: "Shutting Down",
		14: "Updating",
		15: "Docking",
		16: "Go To",
		17: "Zone Clean",
		18: "Room Clean",
		22: "Emptying dust container",
		23: "Washing the mop",
		26: "Going to wash the mop",
		28: "In call",
		29: "Mapping",
		100: "Fully Charged",
	},
	dockTypes: {
		0: "Charging dock",
		1: "Auto-Empty Dock",
		2: "Empty Wash Fill Dock",
		3: "Empty Wash Fill (Dry) Dock",
		5: "Auto-Empty Dock (Q8 Max+)",
		7: "Empty Wash Fill Dry Dock (S8 Pro Ultra)",
		8: "Empty Wash Fill Dry Dock (Q Revo)",
		9: "Empty Wash Fill Dry Dock (Q Revo Pro)",
		14: "Empty Wash Fill Dry Dock (Qrevo Master)",
		16: "Empty Wash Fill Dry Dock (Saros 10R)",
	},
	baseCommands: {
		app_start: { type: "boolean", def: false },
		app_segment_clean: { type: "boolean", def: false },
		app_stop: { type: "boolean", def: false },
		app_pause: { type: "boolean", def: false },
		app_charge: { type: "boolean", def: false },
		app_spot: { type: "boolean", def: false },
		app_zoned_clean: { type: "json" },
		resume_zoned_clean: { type: "boolean", def: false },
		stop_zoned_clean: { type: "boolean", def: false },
		resume_segment_clean: { type: "boolean", def: false },
		stop_segment_clean: { type: "boolean", def: false },
		set_custom_mode: { type: "number", def: 102, states: { 101: "Quiet", 102: "Balanced", 103: "Turbo", 104: "Max", 105: "Off" } },
		find_me: { type: "boolean", def: false },
		app_goto_target: { type: "json" },
		set_clean_motor_mode: { type: "json", def: '{"fan_power":102,"mop_mode":300,"water_box_mode":201}' },
	},
	deviceStates: {
		dock_type: { type: "number", states: {} },
		error_code: { type: "number", states: {} },
		clean_area: { type: "number", unit: "m²" },
		clean_time: { type: "number", unit: "min" },
		battery: { type: "number", unit: "%" },
		state: { type: "number", states: {} },
		fan_power: { type: "number", states: { 101: "Quiet", 102: "Balanced", 103: "Turbo", 104: "Max", 105: "Off" } },
		clean_percent: { unit: "%" },
		water_box_mode: { type: "number", states: { 200: "Off", 201: "Mild", 202: "Moderate", 203: "Intense", 204: "Custom", 205: "Custom", 206: "Custom", 207: "Custom", 208: "Custom", 209: "Custom" } },
		mop_mode: { states: { 300: "Standard", 301: "Deep", 303: "Deep+", 304: "Fast" } },
		carpet_mode: {
			states: {
				'[{"enable":0,"stall_time":10,"current_low":400,"current_high":500,"current_integral":450}]': "off",
				'[{"enable":1,"stall_time":10,"current_low":400,"current_high":500,"current_integral":450}]': "on",
			},
		},
		carpet_clean_mode: {
			states: {
				'{"carpet_clean_mode":0}': "Avoid",
				'{"carpet_clean_mode":1}': "Rise",
				'{"carpet_clean_mode":2}': "Ignore",
			},
		},
		unsave_map_flag: { type: "number" },
		unsave_map_reason: { type: "number" },
		dock_error_status: { type: "number" },
		debug_mode: { type: "number" },
		auto_dust_collection: { type: "number" },
		dust_collection_status: { type: "number" },
		adbumper_status: { type: "string" },
		lock_status: { type: "number" },
		is_locating: { type: "number" },
		map_status: { type: "number" },
		dnd_enabled: { type: "number" },
		lab_status: { type: "number" },
		in_fresh_state: { type: "number" },
		in_returning: { type: "number" },
		in_cleaning: { type: "number" },
		map_present: { type: "number" },
		is_exploring: { type: "number" },
		events: { type: "string" },
		subdivision_sets: { type: "number" },
		repeat: { type: "number" },
		replenish_mode: { type: "number" },
		rdt: { type: "number" },
		camera_status: { type: "number" },
		distance_off: { type: "number" },
		wash_phase: { type: "number" },
		wash_ready: { type: "number" },
		wash_status: { type: "number" },
		back_type: { type: "number" },
		collision_avoid_status: { type: "number" },
		avoid_count: { type: "number" },
		switch_map_mode: { type: "number" },
		charge_status: { type: "number" },
		dry_status: { type: "number" },
		extra_time: { type: "number" },
		rss: { type: "number" },
		dss: { type: "number" },
		common_status: { type: "number" },
		kct: { type: "number" },
		sterilize_status: { type: "number" },
		rst: { type: "number" },
		switch_status: { type: "number" },
		last_clean_t: { type: "string" },
		cleaning_info: { type: "string" },
		exit_dock: { type: "number" },
		dtof_status: { type: "number" },
		seq_type: { type: "number" },
		mop_forbidden_enable: { type: "number" },
		voice_chat_status: { type: "number" },
		corner_clean_mode: { type: "number" },
		home_sec_status: { type: "number" },
		home_sec_enable_password: { type: "number" },
		monitor_status: { type: "number" },
		clean_fluid: { type: "number" },
		water_box_carriage_status: { type: "number" },
		water_box_status: { type: "number" },
		water_shortage_status: { type: "number" },
		cleaned_area: { type: "number", unit: "m²" },
		clean_times: { type: "number" },
	},
	consumables: {
		main_brush_work_time: { unit: "h" },
		side_brush_work_time: { unit: "h" },
		filter_work_time: { unit: "h" },
		filter_element_work_time: { unit: "h" },
		sensor_dirty_time: { unit: "h" },
		main_brush_life: { unit: "%" },
		side_brush_life: { unit: "%" },
		filter_life: { unit: "%" },
		strainer_work_times: { unit: "h" },
		cleaning_brush_work_times: { unit: "%" },
	},
	resetConsumables: new Set([
		"main_brush_work_time",
		"side_brush_work_time",
		"filter_work_time",
		"filter_element_work_time",
		"sensor_dirty_time",
		"dust_collection_work_times",
		"strainer_work_times",
		"cleaning_brush_work_times",
	]),
	cleaningRecords: {
		0: { type: "string" }, // begin
		1: { type: "string" }, // end
		2: { type: "number", unit: "min" }, // duration
		3: { type: "number", unit: "m²" }, // area
		4: { type: "number" }, // error
		5: { type: "number" }, // complete
		6: { type: "number" }, // start_type
		7: { type: "number" }, // clean_type
		8: { type: "number" }, // finish_reason
		9: { type: "number" }, // dust_collection_status

		// Mapped from name
		begin: { type: "string" },
		end: { type: "string" },
		duration: { type: "number", unit: "min" },
		area: { type: "number", unit: "m²" },
		error: { type: "number" },
		complete: { type: "number" },
		start_type: { type: "number" },
		clean_type: { type: "number" },
		finish_reason: { type: "number" },
		dust_collection_status: { type: "number" },

		cleaned_area: { type: "number", unit: "m²" },
		task_id: { type: "number" },
		clean_times: { type: "number" },
		dirty_replenish: { type: "number" },
		manual_replenish: { type: "number" },
		map_flag: { type: "number" },
		wash_count: { type: "number" },
		avoid_count: { type: "number" },
	},
	cleaningInfo: {
		0: { unit: "h" },
		1: { unit: "m²" },
		clean_time: { unit: "h" },
		clean_area: { unit: "m²" },
	},
	firmwareFeatures: {
		111: "isSupportFDSEndPoint",
		112: "isSupportAutoSplitSegments",
		114: "isSupportOrderSegmentClean",
		116: "isMapSegmentSupported",
		119: "isSupportLedStatusSwitch",
		120: "isMultiFloorSupported",
		122: "isSupportFetchTimerSummary",
		123: "isOrderCleanSupported",
		125: "isRemoteSupported",
	},
};
